CREATE OR REPLACE VIEW VIEW_WEIGHBRIDGE_TCODE AS
SELECT 'P' TCODE,
       'RM INWARD' TNAME,
       'SECU,SECF' REQUIRED_GATEPASS,
       '' REQUIRED_ORDER,
       'N' APPROVE,
       'FG TG BP RM SI SM OT' ACC_SCH_STR,
       0 NO_ITEMS,
       'CNTR_REMARK,CNTR_VHCL_NO,PROCESS_CODE,PROCESS_REMARK,GODOWN_CODE,FREIGHT_ADV,TEMP_WBNO_2' INVISIBLE_COLUMN_STR,
       'RM FG SC TG BP' ITEM_NATURE_STR,
       0 OUTWEIGH_RATE,
       'GWI' ESBS_TRANTYPE,
       'ORDER_VRNO' REQUIRED_COLUMN_STR_HEAD,
       'ITEM_CODE' REQUIRED_COLUMN_STR_BODY
  FROM DUAL
UNION ALL
SELECT 'S' TCODE,
       'OUTWARD' TNAME,
       'LADV,SECF,SORD' REQUIRED_GATEPASS,
       '' REQUIRED_ORDER,
       'N' APPROVE,
       '' ACC_SCH_STR,
       1 NO_ITEMS,
       'PROCESS_CODE,PROCESS_REMARK,GODOWN_CODE,FREIGHT_ADV,TEMP_WBNO_2,TP_BOOK_NO,TP_PAGE_NO,PARTYGROSSWT,PARTYTEARWT,PARTYNETWT' INVISIBLE_COLUMN_STR,
       'FG BP RM SI SM OT TG' ITEM_NATURE_STR,
       0 OUTWEIGH_RATE,
       'GWO' ESBS_TRANTYPE,
       'ACC_CODE,LADV' REQUIRED_COLUMN_STR_HEAD,
       'CNTR_CODE' REQUIRED_COLUMN_STR_BODY
  FROM DUAL
UNION ALL
SELECT 'I' TCODE,
       'STORES MATERIAL' TNAME,
       '' REQUIRED_GATEPASS,
       '' REQUIRED_ORDER,
       'N' APPROVE,
       'G C E' ACC_SCH_STR,
       0 NO_ITEMS,
       'CNTR_CODE, CNTR_REMARK,CNTR_VHCL_NO,PROCESS_CODE,PROCESS_REMARK,GODOWN_CODE,FREIGHT_ADV,TEMP_WBNO_2,RAKENO,TP_BOOK_NO,TP_PAGE_NO' INVISIBLE_COLUMN_STR,
       'SI CI' ITEM_NATURE_STR,
       0 OUTWEIGH_RATE,
       'GWI' ESBS_TRANTYPE,
       '' REQUIRED_COLUMN_STR_HEAD,
       '' REQUIRED_COLUMN_STR_BODY
  FROM DUAL
UNION ALL
SELECT 'Y' TCODE,
       'YARD TRANSFER ' TNAME,
       '' REQUIRED_GATEPASS,
       '' REQUIRED_ORDER,
       'Y' APPROVE,
       'D' ACC_SCH_STR,
       1 NO_ITEMS,
       'CNTR_CODE, CNTR_REMARK,CNTR_VHCL_NO,PROCESS_CODE,PROCESS_REMARK,GODOWN_CODE,FREIGHT_ADV,TEMP_WBNO_2,VHCL_TYPE,TP_BOOK_NO,TP_PAGE_NO,PARTYGROSSWT,PARTYTEARWT,PARTYNETWT' INVISIBLE_COLUMN_STR,
       'SM RM SC FG BP FG ' ITEM_NATURE_STR,
       0 OUTWEIGH_RATE,
       'GWY' ESBS_TRANTYPE,
       '' REQUIRED_COLUMN_STR_HEAD,
       'ORDER_VRNO,ORDI,ITEM_CODE' REQUIRED_COLUMN_STR_BODY
  FROM DUAL
UNION ALL
SELECT 'W' TCODE,
       'CAPTIVE(INTER DIV) TRANSFER-RECEIVED' TNAME,
       '' REQUIRED_GATEPASS,
       '' REQUIRED_ORDER,
       'Y' APPROVE,
       'D F' ACC_SCH_STR,
       1 NO_ITEMS,
       'CNTR_CODE, CNTR_REMARK,CNTR_VHCL_NO,PROCESS_CODE,PROCESS_REMARK,GODOWN_CODE,FREIGHT_ADV,TEMP_WBNO_2,VHCL_TYPE,RAKENO,TP_BOOK_NO,TP_PAGE_NO,PARTYGROSSWT,PARTYTEARWT,PARTYNETWT' INVISIBLE_COLUMN_STR,
       'RM SC TG SI BP SM FG' ITEM_NATURE_STR,
       0 OUTWEIGH_RATE,
       'GWY' ESBS_trantype,
       'ORDI,ORDER_VRNO' required_column_str_head,
       'ORDI,ORDER_VRNO,ITEM_CODE' required_column_str_body
  FROM DUAL

UNION ALL
SELECT 'G' TCODE,
       'GENERAL PURPOSE' TNAME,
       '' REQUIRED_GATEPASS,
       '' REQUIRED_ORDER,
       'Y' APPROVE,
       NULL ACC_SCH_STR,
       1 NO_ITEMS,
       'CNTR_CODE, CNTR_REMARK,CNTR_VHCL_NO,PROCESS_CODE,PROCESS_REMARK,GODOWN_CODE,FREIGHT_ADV,TEMP_WBNO_2,TP_BOOK_NO,TP_PAGE_NO,PARTYGROSSWT,PARTYTEARWT,PARTYNETWT' INVISIBLE_COLUMN_STR,
       'SM RM SC SI BP' ITEM_NATURE_STR,
       0 OUTWEIGH_RATE,
       'GWY' ESBS_TRANTYPE,
       '' REQUIRED_COLUMN_STR_HEAD,
       'ORDI,ORDER_VRNO' REQUIRED_COLUMN_STR_BODY
  FROM DUAL
UNION ALL

SELECT 'R' TCODE,
       'SALE RETURN' TNAME,
       '' REQUIRED_GATEPASS,
       '' REQUIRED_ORDER,
       'N' APPROVE,
       NULL ACC_SCH_STR,
       0 NO_ITEMS,
       'CNTR_CODE, CNTR_REMARK,CNTR_VHCL_NO,PROCESS_CODE,PROCESS_REMARK,GODOWN_CODE,FREIGHT_ADV,TEMP_WBNO_2,VHCL_TYPE,RAKENO,TP_BOOK_NO,TP_PAGE_NO,PARTYGROSSWT,PARTYTEARWT,PARTYNETWT' INVISIBLE_COLUMN_STR,
       'RM SC FG SM ' ITEM_NATURE_STR,
       0 OUTWEIGH_RATE,
       'GWI' ESBS_TRANTYPE,
       '' REQUIRED_COLUMN_STR_HEAD,
       '' REQUIRED_COLUMN_STR_BODY
  FROM DUAL
UNION ALL
SELECT 'U' TCODE,
       'PURCHASE RETURN' TNAME,
       '' REQUIRED_GATEPASS,
       '' REQUIRED_ORDER,
       'N' APPROVE,
       'C E' ACC_SCH_STR,
       0 NO_ITEMS,
       'CNTR_CODE, CNTR_REMARK,CNTR_VHCL_NO,PROCESS_CODE,PROCESS_REMARK,GODOWN_CODE,FREIGHT_ADV,TEMP_WBNO_2,RAKENO,TP_BOOK_NO,TP_PAGE_NO,PARTYGROSSWT,PARTYTEARWT,PARTYNETWT' INVISIBLE_COLUMN_STR,
       'RM SI SC ' ITEM_NATURE_STR,
       0 OUTWEIGH_RATE,
       'GWO' ESBS_TRANTYPE,
       '' REQUIRED_COLUMN_STR_HEAD,
       '' REQUIRED_COLUMN_STR_BODY
  FROM DUAL
UNION ALL

SELECT 'C' TCODE,
       'CAPTIVE(INTER DIV) TRANSFER ISSUES' TNAME,
       '' REQUIRED_GATEPASS,
       '' REQUIRED_ORDER,
       'Y' APPROVE,
       NULL ACC_SCH_STR,
       0 no_items,
       'PROCESS_CODE,PROCESS_REMARK,GODOWN_CODE,FREIGHT_ADV,TEMP_WBNO_2,RAKENO,TP_BOOK_NO,TP_PAGE_NO,PARTYGROSSWT,PARTYTEARWT,PARTYNETWT' INVISIBLE_COLUMN_STR,
       'FG BP RM SI SM OT TG' ITEM_NATURE_STR,
       0 OUTWEIGH_RATE,
       'GWO' ESBS_trantype,
       '' required_column_str_head,
       'ORDI,ORDER_VRNO,CNTR_CODE' required_column_str_body
  FROM DUAL

